version: "3.8"

networks:
    wiki-db:
        name: postgres
        external: true
    wiki:
        name: wiki

services:
    wiki:
        image: wiki:development
        build:
            context: .
        env_file:
            - .env
        networks:
            - wiki
            - wiki-db
        ports:
            - 3000:3000

